language:
  - objective-c

env:
  - CONFIG=Release
  - CONFIG=Debug

install:
  - brew update
  - brew tap homebrew/science
  - brew install opencv

script:
  - cmake -H. -B_builds -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build _builds --config ${CONFIG}
  - cd _builds
  - ctest -VV -C ${CONFIG}
